---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# 2022 Scientific Computing Course Final Project

<!-- badges: start -->
<!-- badges: end -->

Author: Thales Moreira de Lima (thalesdrago@gmail.com)
Instructors: Sara Mortara and Andrea Sanchéz-Tapia
<<<<<<< HEAD

This project is the final assignment of the Scientific Computing course that took place during 2022 as part of the Serrapilheira/ICTP-SAIFR Quantitative Biology Program.

The idea of this project is to use biogeographic models to combine biogeographic data and a phylogeny and infer the ancestral range of the palms (Arecaceae) of the subfamily Arecaceae.

August, 2022

=======
This project is the final assignment of the Scientific Computing course that took place during 2022 as part of the Serrapilheira/ICTP-SAIFR Quantitative Biology Program.

August, 2022

>>>>>>> 59dd7f124cb050a458796313bab7a76646180e06
## Folder structure

```
project/
     ├── biblio/
*    ├── data/
     │   ├── GIS
*    │   ├── raw
*    │   └── processed
     ├── docs/
*    ├── figs/
     ├── func/
     ├── R/
*    ├── output/
*    └── README.md
```
- In the `biblio` directory you will find the bibliographical library in .bib format.
- In the `data` directory you will find the raw data of the project in the `raw` directory, the processed one in the `processed` directory. And the `GIS` directory contains spatial data. 
- In the `docs` directory you will find text files like .pdf and .Rmd files.
- In the `figs` directory you will find image files like .png files.
- In the `fun` directory you will find R scripts that define functions called by other scripts.
- In the `R` directory you will find the main R script files that are used to conduct the analyzes.
- The `README` file is this very one that you are reading now, and its purpose is to explain very briefly what is this project about and which is which structure

## 

